print_stats: true

densify:
  frequency: 20
  start_iteration: 0
  end_iteration: 500
  clone_grad_threshold: 0.0001
  split_grad_threshold: 1e8
  split_extreme_shape_grad_threshold: 1e8
  relative_size_threshold: 0.2
  split_n_gaussians: 2

  anisotropy_threshold: 3.0
  size_min: 0.002
  size_max: 0.2

prune:
  frequency: 100
  start_iteration: -1
  end_iteration: -1
  prune_opacity_threshold: 0.01
  
decay_opacities:
  frequency: 30
  gamma: 0.95
  start_iteration: -1
  end_iteration: -1

reset_opacities:
  frequency: 300
  start_iteration: -1
  end_iteration: -1
  new_max_density: 0.2

prune_scale:
  frequency: 100
  start_iteration: -1
  end_iteration: -1
  prune_scale_threshold: 1.0