optimizer:
  iterations: 700
  params:
    centers_lr: 0.0
    scales_lr: 0.0
    quats_lr: 0.0
    opacities_lr: 0.0
    sh_coeffs_lr: 0.0
    normals_lr: 0.003

  scheduler:
    type: cosine
    min_factor: 1.0

