optimizer:
  iterations: 150
  params:
    centers_lr: 0.0002
    scales_lr: 0.0002
    quats_lr: 0.0002
    opacities_lr: 0.0005
    sh_coeffs_lr: 0.003
    normals_lr: 0.003

  scheduler:
    type: cosine
    min_factor: 0.1

