optimizer:
  iterations: 500
  params:
    centers_lr: 0.0002
    scales_lr: 0.0002
    quats_lr: 0.0002
    opacities_lr: 0.005
    normals_lr: 0.001
    albedos_lr: 0.01
    roughnesses_lr: 0.01

  scheduler:
    type: cosine
    min_factor: 0.1
