optimizer:
  iterations: 800
  warmup_iterations: 200
  params:
    centers_lr: 0.0
    scales_lr: 0.0
    quats_lr: 0.0
    normals_lr: 1e-6

    opacities_lr: 0.0
    albedos_lr: 0.02
    roughnesses_lr: 0.02
    metallics_lr: 0.0

    envmap:
      sg_lobe_lr: 0.02
      sg_lambda_lr: 0.02
      sg_mu_lr: 0.02

      data_lr: 0.02

  scheduler:
    type: cosine
    min_factor: 0.5
