optimizer:
  iterations: 300  
  params:
    centers_lr: 1e-6
    scales_lr: 1e-6
    quats_lr: 1e-6
    normals_lr: 1e-5

    opacities_lr: 1e-5
    albedos_lr: 0.02
    roughnesses_lr: 0.02

    envmap:
      sg_lobe_lr: 0.05
      sg_lambda_lr: 0.05
      sg_mu_lr: 0.05

      data_lr: 0.02

  scheduler:
    type: cosine
    min_factor: 0.5
